<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-23T21:40:09 EET" name="Default suite" finished-at="2024-10-23T21:40:14 EET" duration-ms="5514">
    <groups>
    </groups>
    <test started-at="2024-10-23T21:40:09 EET" name="Default test" finished-at="2024-10-23T21:40:14 EET" duration-ms="5514">
      <class name="MyClass">
        <test-method is-config="true" signature="Setup()[pri:0, instance:MyClass@2c532cd8]" started-at="2024-10-23T21:40:09 EET" name="Setup" finished-at="2024-10-23T21:40:14 EET" duration-ms="5278" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="CheckLanguage()[pri:1, instance:MyClass@2c532cd8]" started-at="2024-10-23T21:40:14 EET" name="CheckLanguage" finished-at="2024-10-23T21:40:14 EET" duration-ms="64" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckLanguage -->
        <test-method signature="CheckTheCurrencyIsSAR()[pri:2, instance:MyClass@2c532cd8]" started-at="2024-10-23T21:40:14 EET" name="CheckTheCurrencyIsSAR" finished-at="2024-10-23T21:40:14 EET" duration-ms="53" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckTheCurrencyIsSAR -->
        <test-method signature="CheckContactNumber()[pri:3, instance:MyClass@2c532cd8]" started-at="2024-10-23T21:40:14 EET" name="CheckContactNumber" finished-at="2024-10-23T21:40:14 EET" duration-ms="32" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckContactNumber -->
        <test-method signature="CheckQitaf()[pri:4, instance:MyClass@2c532cd8]" started-at="2024-10-23T21:40:14 EET" name="CheckQitaf" finished-at="2024-10-23T21:40:14 EET" duration-ms="49" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at MyClass.CheckQitaf(MyClass.java:58)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckQitaf -->
        <test-method is-config="true" signature="ok()[pri:0, instance:MyClass@2c532cd8]" started-at="2024-10-23T21:40:14 EET" name="ok" finished-at="2024-10-23T21:40:14 EET" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ok -->
      </class> <!-- MyClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
